### ISSUE TITLE
No occwl

### ISSUE THREAD

**Issue by zeroright** [AutodeskAILab/BRepNet#1]
Hello,

I want to run this project, but I can't find the occwl in conda or github.
I really appreciate it if you have any help about occwl.

Thank You!

**Comment by JoeLambourne** [comment]
Hi @zeroright,

Could you try
```
conda install -c lambouj -c conda-forge occwl
```
and let me know if it works.  The source code will be published soon

**Comment by zeroright** [comment]
Thanks for your response!
Maybe is my network problem, so I found and download the occwl package in the link https://anaconda.org/lambouj/occwl.
Now I can use the occwl.

But in the occwl,  I don't understand why should use the "from deprecate import deprecated"? 
And I comment out this line "from deprecate import deprecated", the project is also can be runed.

Looking forward to your reply!

**Comment by JoeLambourne** [comment]
Hi @zeroright,

Sorry you have been having problems getting this working. 

> But in the occwl, I don't understand why should use the "from deprecate import deprecated"?

That's in the `pydeprecate` package.   I also had trouble finding the correct package to install for this.  It sounds like you are building your own conda or pip environment.   Using 
```
conda env create -f environment.yml
``` 
everything should work out of the box.

@pradeep-pyro deprecated the functions.    The occwl packages is shared between BRepNet and [UV-Net](https://github.com/AutodeskAILab/UV-Net)

**Comment by pradeep-pyro** [comment]
Hi @zeroright , the occwl library is now publicly available here: https://github.com/AutodeskAILab/occwl.

However, as far as running BRepNet is concerned, you don't have to manually install any dependency. The easiest way to get everything working is to install Anaconda Python (https://docs.anaconda.com/anaconda/install/) and create the environment like Joe suggested above.

After that you can run `conda activate brepnet` which will have all the dependencies that you need installed automatically.

**Comment by JoeLambourne** [comment]
@zeroright ,

Is there anything further we can do to help here?  Is it ok to close this?

**Comment by zeroright** [comment]
Thanks for your replay! ( @pradeep-pyro @JoeLambourne )
And I think this question can be closed.

**Comment by sanweishuwu100** [comment]
> Hi @zeroright,
> 
> Could you try
> 
> ```
> conda install -c lambouj -c conda-forge occwl
> ```
> 
> and let me know if it works. The source code will be published soon



> Hi @zeroright,
> 
> Could you try
> 
> ```
> conda install -c lambouj -c conda-forge occwl
> ```
> 
> and let me know if it works. The source code will be published soon



> Hi @zeroright,
> 
> Could you try
> 
> ```
> conda install -c lambouj -c conda-forge occwl
> ```
> 
> and let me know if it works. The source code will be published soon

When I use the above methodt, the following problems will appear.
(base) PS C:\Users\19890> conda install -c lambouj -c conda-forge occwl
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Can anyone help me? Thank you.
