### ISSUE TITLE
find_and_display_segmentation.ipynb => AttributeError

### ISSUE THREAD

**Issue by cteqeu** [AutodeskAILab/BRepNet#11]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_23316/310475324.py in <module>
      6 file_stem = step_file_stems[example_index]
      7 print(f"Viewing example {file_stem}")
----> 8 viewer = JupyterSegmentationViewer(file_stem, step_folder, seg_folder=step_folder, logit_folder=logits_folder)

~\BRepNet\visualization\jupyter_segmentation_viewer.py in __init__(self, file_stem, step_folder, seg_folder, logit_folder)
     76         assert len(solids) == 1, "Expect only 1 solid"
     77         self.solid = solids[0]
---> 78         self.entity_mapper = EntityMapper(self.solid.topods_solid())
     79 
     80         self.seg_folder = seg_folder

AttributeError: 'Solid' object has no attribute 'topods_solid'

**Comment by akashaero** [comment]
If it still helps,

replace 'topods_solid()' with 'topods_shape()' and try again. It worked for me
