### ISSUE TITLE
JupyterSegmentationViewer using outdated Solid class method 'topods_solid()'

### ISSUE THREAD

**Issue by Danelrf** [AutodeskAILab/BRepNet#12]
As per the title,

the JuputerSegmentationViewer class uses the topods_solid() method, which was deprecated and then deleted.

topods_shape() should be used instead.

**Comment by akashaero** [comment]
If it still helps,

replace 'topods_solid()' with 'topods_shape()' and try again. It worked for me

**Comment by JoeLambourne** [comment]
Hi @Danelrf  and @akashaero,

Sorry for not spotting this earlier.   I missed the notification for your questions.  Thank you for the detailed error report and workaround.

In PR #13 I've updated everything to work with the latest version of the occwl library.  You should be able to pull from `master` now and everything should be working again.   

It's possible you might need to update your environment to occwl v1.0.0.  I tested by deleting the environment and rebuilding it with
```
conda env create -f environment.yml
```

Let me know if you have any issues.
