### ISSUE TITLE
AssertionError raised when processing STEP data

### ISSUE THREAD

**Issue by QuanYuhan** [AutodeskAILab/BRepNet#16]
Hi, 

I tried to run `pipeline.extract_brepnet_data_from_step` to process the step files from [Fusion 360 Gallery Assembly Joint Dataset]( https://github.com/AutodeskAILab/Fusion360GalleryDataset/blob/master/docs/assembly_joint.md) without seg files , but I found that when processing some specific step files, the following error will occur

> File "/data/brepnet/pipeline/extract_brepnet_data_from_step.py", line 65, in process
    body = scale_utils.scale_solid_to_unit_box(body)
  File "/data/brepnet/utils/scale_utils.py", line 24, in scale_solid_to_unit_box
    solid = solid.scale_to_unit_box(copy=True)
  File "/home/anaconda3/envs/brepnet/lib/python3.7/site-packages/occwl/base.py", line 641, in scale_to_unit_box
    return self.scale_to_box(1.0, copy=copy)
  File "/home/anaconda3/envs/brepnet/lib/python3.7/site-packages/occwl/base.py", line 625, in scale_to_box
    return self._apply_transform(trsf_to_apply, copy=copy)
  File "/home/anaconda3/envs/brepnet/lib/python3.7/site-packages/occwl/shape.py", line 326, in _apply_transform
    return type(self)(transformed_shape)
  File "/home/anaconda3/envs/brepnet/lib/python3.7/site-packages/occwl/solid.py", line 35, in __init__
    assert isinstance(shape, TopoDS_Solid)

I sorted out some error step files in this [Google Drive link](https://drive.google.com/drive/folders/1_Cakff0LI7Red6e_WYpbqY3wjK-s9G3v?usp=sharing). I tried using occwl 1.0.0 and 2.0.0, but the problem still exists.

Although the problem appears to be caused by [occwl](https://github.com/AutodeskAILab/occwl), since it's also open sourced by AutodeskAILab, maybe someone has an idea how to solve it?

Thanks in advance!

**Comment by JoeLambourne** [comment]
Hi @QuanYuhan,

Wow.   That's very odd.   So the class is an `occwl.Solid` but after the transform is applied it has mutated to something else.   I will need to debug with your example data.

**Comment by JoeLambourne** [comment]
Hi @QuanYuhan,

I'm looking at the problem now.   Did you create the models yourself?  I'm wondering if they are suitable for using as unit test data.

**Comment by JoeLambourne** [comment]
Hi @QuanYuhan,

I have made PR#19 which should fix this issue.   Could you pull the latest version and confirm all is well?

Thank you for you help reporting this.

**Comment by QuanYuhan** [comment]
Hi, @JoeLambourne 

I tested the latest version of the code on the whole [Fusion 360 Gallery Assembly Joint Dataset](https://github.com/AutodeskAILab/Fusion360GalleryDataset/blob/master/docs/assembly_joint.md) and it's working well now.

Thank you for you help!

**Comment by JoeLambourne** [comment]
Hi, @QuanYuhan,

Thank you for confirming things are working.   Good luck with your project!  If you publish a paper then ping with the arxiv link.  I'm excited to see how this work is getting used.

Joe
