### ISSUE TITLE
Possible broken dependencies with environment.yml

### ISSUE THREAD

**Issue by samParry** [AutodeskAILab/BRepNet#17]
Creating a conda environment from the .yml file seems to install versions of packages that no longer work together with the BRepNet source code. I've followed the installation instructions on several machines and get different error messages on each machine relating to broken dependencies in the site packages installed from the .yml. Can someone verify the installation or update the .yml to specify the package versions that worked correctly when the paper was published?

**Comment by JoeLambourne** [comment]
Hi @samParry,

Yes.  It was working fine, but towards the end of last year we started to have issues with the `occwl` package.  I've been needing to install that with mamba.    Let me see what I can do to get BRepNet working again

**Comment by JoeLambourne** [comment]
Hi @samParry,

Is the problem you are having related to the command 

```
conda env create -f environment.yml
```
just hanging and never installing anything?  I'm having trouble with this now, but I want to verify you are seeing a similar issue or something different?

**Comment by samParry** [comment]
Hi @JoeLambourne 
Yes, I've had issues with very long wait times up to several hours. I also getting site package errors when running the training commands from the **Training the model** section of the ReadMe. I found that you have to set pytorch-lightning to 1.6.4 to get the model to train.

**Comment by JoeLambourne** [comment]
@samParry 

>OSError: [Errno 24] Too many open files

I get that sometimes when using many threads.  I have double checked files opened by the dataloader do get closed.   The workaround is setting
```
ulimit -Sn 10000
```
