### ISSUE TITLE
how to get the ground truth seg label of the top-face

### ISSUE THREAD

**Issue by ealwen** [AutodeskAILab/BRepNet#20]
Thanks for your great work! But I have a trouble in associating the face to the semantic segmentation label. I know there are .step file and the related .seg file. I do not confirm if I read step by pythonocc and get the top-face list ,the face index  in the list is same to the .seg row?

**Comment by ealwen** [comment]
That's true!

**Comment by wll0307** [comment]
@ealwen 
"I want to ask you a question. If I want to build my own dataset, how can I obtain the .seg files, which are the labels? Do you know?"

**Comment by ealwen** [comment]
> @ealwen "I want to ask you a question. If I want to build my own dataset, how can I obtain the .seg files, which are the labels? Do you know?"

Hello, Supposed that you have a CAD model in .STEP format and you know the truth label assciated with  each face of this CAD model. To get a similar .seg file like this project, a simple method is that traversal the CAD model and get all the faces of the CAD model, and in this way, you can get something like a face list (or other data  structure) .  You can then bind information about the face's thuth label you have known  to each element of the list above (Just like a dict structure in Python, the key is the face you traversal  from the CAD model or the index of the face list ,the value is the truth label to the face. ). Finally, we can save those information to a file ,such as a file with the suffix '.seg',or something you like. 

[pythonocc](https://github.com/tpaviot/pythonocc-core) is a good tool to help you well,which can read  a CAD model in STEP format and traversal it to obtain model's faces. There is a relavant project [AAGNet](https://github.com/whjdark/AAGNet) you can refer to. [AAGNet](https://github.com/whjdark/AAGNet) automatically generated some 3D models, and saved the labels of each face of the CAD model according to the logic of generating process.

Hope this reply can be of some help to you.
