### ISSUE TITLE
How to visualize the brep data?

### ISSUE THREAD

**Issue by StevenZzz07** [AutodeskAILab/BRepNet#3]
Hi, sorry to bother, firstly thanks for your outstanding works. The visualization results in your paper are very vivid as follows:
![87a259f7f2ef84dfc3ec90a45ec6e4d](https://user-images.githubusercontent.com/56421441/134484593-8089a7d0-8ca4-47cf-8500-4c29b12f4910.png)
So i am wondering how to draw this kind of rendering images. Any softwares or public codes could be utilized to get them? Thanks in advance :)

**Comment by karldd** [comment]
Unfortunately this was done manually by first [generating a drawing in Fusion 360](https://knowledge.autodesk.com/support/fusion-360/troubleshooting/caas/sfdcarticles/sfdcarticles/How-to-create-a-2D-drawing-from-your-CAD-file-in-Fusion-360.html), then adding the labels, coloring etc in Adobe Illustrator.

**Comment by StevenZzz07** [comment]
Thanks a lot! I will try it right away.
